In [1]:
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

**Tensors**

In [2]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
tensor = torch.Tensor([[1,2,3],[4,5,6]])
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
arr * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [5]:
tensor * 5

tensor([[ 5., 10., 15.],
        [20., 25., 30.]])

In [6]:
arr.sum()

np.int64(21)

In [7]:
tensor.sum()

tensor(21.)

In [8]:
tensor = torch.from_numpy(arr)
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
torch.ones((2,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
np.random.random((2,4))

array([[0.42545118, 0.80526664, 0.13243215, 0.15567139],
       [0.21385357, 0.02550523, 0.7993077 , 0.90519711]])

In [12]:
torch.rand((2,4))

tensor([[0.4444, 0.4554, 0.4356, 0.9194],
        [0.3345, 0.6365, 0.6413, 0.3498]])

In [13]:
arr.shape

(2, 3)

In [14]:
arr.dtype

dtype('int64')

In [15]:
arr.device

'cpu'

In [16]:
tensor.device

device(type='cpu')

In [17]:
X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
X_train_scaled

array([[-0.21372451,  0.27461086, -0.14551411, ...,  1.3472499 ,
         1.03294928,  1.44582697],
       [-0.93323761, -1.59849633, -0.96141531, ..., -1.26169704,
        -1.21635326, -0.98588365],
       [-0.80898435, -0.16328813, -0.80995058, ..., -0.45593079,
         0.21402845, -0.90932879],
       ...,
       [-0.75697135, -0.13119082, -0.78568274, ..., -0.79131517,
         0.59775135, -0.77098321],
       [-0.70206874, -0.60806511, -0.72794204, ..., -0.6930804 ,
        -1.88864826, -0.60310932],
       [ 1.08948999,  0.38924411,  1.35072318, ...,  1.21616976,
         0.50260055,  1.93249718]], shape=(455, 30))

In [19]:
y_train

array([0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,

In [20]:
X_train_scaled_tensor = torch.from_numpy(X_train_scaled).float()
X_test_scaled_tensor = torch.from_numpy(X_test_scaled).float()
y_train_tensor = torch.from_numpy(y_train).float().unsqueeze(1)
y_test_tensor = torch.from_numpy(y_test).float().unsqueeze(1)


In [21]:
train_dataset = TensorDataset(X_train_scaled_tensor, y_train_tensor)

In [22]:
X_train_scaled_tensor.shape

torch.Size([455, 30])

In [23]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [24]:
class BCNet(nn.Module):

    def __init__(self):
        super(BCNet, self).__init__()

        self.fc1 = nn.Linear(30, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 1)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.sigmoid(self.fc3(x))

        return x

In [25]:
model = BCNet()

In [26]:
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [27]:
epochs = 50

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for x_batch, y_batch in train_loader:
        optimizer.zero_grad()

        preds = model(x_batch)
        loss = criterion(preds, y_batch)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f'Epoch {epoch+1}: Loss was {running_loss / len(train_loader)}')

Epoch 1: Loss was 0.61137721935908
Epoch 2: Loss was 0.4741330862045288
Epoch 3: Loss was 0.3187950124343236
Epoch 4: Loss was 0.1960206538438797
Epoch 5: Loss was 0.15478466749191283
Epoch 6: Loss was 0.09613393284380436
Epoch 7: Loss was 0.08424328615268072
Epoch 8: Loss was 0.07288281687845787
Epoch 9: Loss was 0.06840373029311499
Epoch 10: Loss was 0.06161208792279164
Epoch 11: Loss was 0.05918434113264084
Epoch 12: Loss was 0.05569921247661114
Epoch 13: Loss was 0.05081042831297964
Epoch 14: Loss was 0.049586124283572036
Epoch 15: Loss was 0.04601433587570985
Epoch 16: Loss was 0.04493774191165964
Epoch 17: Loss was 0.042374356339375176
Epoch 18: Loss was 0.0411846775872012
Epoch 19: Loss was 0.03886100030504167
Epoch 20: Loss was 0.03749646469950676
Epoch 21: Loss was 0.03586148122946421
Epoch 22: Loss was 0.03467884945372741
Epoch 23: Loss was 0.03324857278882216
Epoch 24: Loss was 0.03292325126628081
Epoch 25: Loss was 0.030332212014279016
Epoch 26: Loss was 0.02889173959071437